version: 3

tasks:
  build:
    cmds:
      - pnpm build

  publish:
    deps:
      - build
    desc: Publish package to npm registry
    cmds:
      - pnpm publish --access public --no-git-check

  version:patch:
    desc: Increment patch version number
    cmds:
      - pnpm version patch
